/**
 * Renders the HTML structure for an arbitrary field inside a form, this
 * includes a <label> and ability to show an error message, the however
 * children can be entirly arbitary
 */
export default function Field({
	/** Extra classes to apply to the outermost <div> wrapper */
	className = '',
	name,

	/** id of the input being wrapped, used to generate htmlFor of <label> */
	id = `__form_field_${name}`,

	/**
	 * Human readable string to render as <label>
	 * Can also be set to jsx <elements> in order to have custom content inside the label
	 */
	label,

	/**
	 * If truthy, will display an error message above the field's children
	 * Should be set to the string to display (see also errorMsg)
	 */
	error,

	/**
	 * If set, will override the error and display set errorMsg as the error content
	 * when `error` prop is truty
	 * Useful when 'error' is autogenerated (eg, by zod) and is too verbose, so needs
	 * to be overridden
	 */
	errorMsg,

	/**
	 * The actual content of the field - should be the interactive element that
	 * lets user input a value
	 */
	children,

	/**
	 * If set to a callback function, a small 'clear' button will be rendered by
	 * the label, and the callback will be triggered when clear is pressed
	 */
	onClear,
}) {
	let errorContent = error ? (
		<FieldErrorMessage>{errorMsg || error}</FieldErrorMessage>
	) : null

	let clearElm = ''
	if (onClear) {
		clearElm = (
			<span onClick={onClear} className="underline text-xs cursor-pointer">
				Clear
			</span>
		)
	}

	if (!label) {
		return (
			<div className={className || ''} id={id}>
				<div className="flex justify-between items-center">
					{errorContent}
					{clearElm}
				</div>
				{children}
			</div>
		)
	}

	return (
		<label id={id} htmlFor={id} className={`block mt-1.5 ${className}`}>
			<div className="block mb-[2px] text-sm font-[700] text-light-900 font-lato flex justify-start items-center gap-2">
				{label} <div className="flex-grow" /> {errorContent} {clearElm}
			</div>
			<div>{children}</div>
		</label>
	)
}

export function FieldErrorMessage({ children }) {
	return (
		<span className="ml-1 px-1.5 py-0.5 bg-red-100 rounded-27xl font-lato text-xs font-[700] text-red-900">
			{children}
		</span>
	)
}